#!/bin/bash

# Check if arguments are provided
if [ $# -ne 2 ]; then
    echo "Usage: ./generate_schemas.sh <proto_dir> <output_dir>"
    exit 1
fi

EXECUTABLE_PATH=~/go/bin/protoc-gen-jsonschema
PROTO_FILES=$(ls -m $1 | grep -o '[^ ]*\.proto' | tr ', ' ' ')

# Check if file exists
if [ ! -f "$EXECUTABLE_PATH" ]; then
    echo "Installing 'protoc-gen-jsonschema'..."
    go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema@latest
fi

mkdir -p $2/schemas

# Generate schemas in $2/schemas from proto files in $1
for file in $1/*; do
    if [ -d "$file" ]; then
        for subfile in $file/*; do
            if [ -f "$subfile" ]; then
                protoc \
                    --plugin=$EXECUTABLE_PATH \
                    --proto_path=$1 \
                    --jsonschema_out=$2/schemas \
                    --jsonschema_opt=enforce_oneof \
                    --jsonschema_opt=file_extension=schema.json \
                    --jsonschema_opt=disallow_additional_properties \
                    --jsonschema_opt=disallow_bigints_as_strings \
                    $subfile
            fi
        done
    fi
done
