name: Run Tests

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Main Repository
              uses: actions/checkout@v4

            - name: Clone telemetry-serializers
              uses: actions/checkout@v4
              with:
                  repository: "eagletrt/telemetry-serializers"
                  path: telemetry-serializers

            - name: Setup Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12
                  cache: "pip"

            - name: Install 'protoc'
              run: |
                  DEBIAN_FRONTEND=noninteractive
                  sudo apt update
                  sudo apt install -y protobuf-compiler

            - name: Install dependencies
              run: |
                pip install protobuf==3.20.0
                pip install -r requirements.txt

            - name: Generate code
              run: python3 src/generator/main.py telemetry-serializers/proto/ serializers

            - name: Genereate *.pb2.py files
              run: chmod +x ./scripts/compile_proto.sh && ./scripts/compile_proto.sh

            - name: Run tests
              run: pytest --verbose
