// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bar.proto

#include "bar.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_bar_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MyMessage_EnumMapEntry_DoNotUse_bar_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_bar_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MyMessage_StringMapEntry_DoNotUse_bar_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_bar_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MyMessage_StructMapEntry_DoNotUse_bar_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_bar_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MySmallMessage_bar_2eproto;
namespace bar {
class MySmallMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MySmallMessage> _instance;
} _MySmallMessage_default_instance_;
class MyMessage_StringMapEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MyMessage_StringMapEntry_DoNotUse> _instance;
} _MyMessage_StringMapEntry_DoNotUse_default_instance_;
class MyMessage_EnumMapEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MyMessage_EnumMapEntry_DoNotUse> _instance;
} _MyMessage_EnumMapEntry_DoNotUse_default_instance_;
class MyMessage_StructMapEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MyMessage_StructMapEntry_DoNotUse> _instance;
} _MyMessage_StructMapEntry_DoNotUse_default_instance_;
class MyMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MyMessage> _instance;
} _MyMessage_default_instance_;
}  // namespace bar
static void InitDefaultsscc_info_MyMessage_bar_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bar::_MyMessage_default_instance_;
    new (ptr) ::bar::MyMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bar::MyMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<4> scc_info_MyMessage_bar_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 4, 0, InitDefaultsscc_info_MyMessage_bar_2eproto}, {
      &scc_info_MySmallMessage_bar_2eproto.base,
      &scc_info_MyMessage_StringMapEntry_DoNotUse_bar_2eproto.base,
      &scc_info_MyMessage_EnumMapEntry_DoNotUse_bar_2eproto.base,
      &scc_info_MyMessage_StructMapEntry_DoNotUse_bar_2eproto.base,}};

static void InitDefaultsscc_info_MyMessage_EnumMapEntry_DoNotUse_bar_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bar::_MyMessage_EnumMapEntry_DoNotUse_default_instance_;
    new (ptr) ::bar::MyMessage_EnumMapEntry_DoNotUse();
  }
  ::bar::MyMessage_EnumMapEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MyMessage_EnumMapEntry_DoNotUse_bar_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MyMessage_EnumMapEntry_DoNotUse_bar_2eproto}, {}};

static void InitDefaultsscc_info_MyMessage_StringMapEntry_DoNotUse_bar_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bar::_MyMessage_StringMapEntry_DoNotUse_default_instance_;
    new (ptr) ::bar::MyMessage_StringMapEntry_DoNotUse();
  }
  ::bar::MyMessage_StringMapEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MyMessage_StringMapEntry_DoNotUse_bar_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MyMessage_StringMapEntry_DoNotUse_bar_2eproto}, {}};

static void InitDefaultsscc_info_MyMessage_StructMapEntry_DoNotUse_bar_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bar::_MyMessage_StructMapEntry_DoNotUse_default_instance_;
    new (ptr) ::bar::MyMessage_StructMapEntry_DoNotUse();
  }
  ::bar::MyMessage_StructMapEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MyMessage_StructMapEntry_DoNotUse_bar_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MyMessage_StructMapEntry_DoNotUse_bar_2eproto}, {
      &scc_info_MySmallMessage_bar_2eproto.base,}};

static void InitDefaultsscc_info_MySmallMessage_bar_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bar::_MySmallMessage_default_instance_;
    new (ptr) ::bar::MySmallMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bar::MySmallMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MySmallMessage_bar_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MySmallMessage_bar_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_bar_2eproto[5];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_bar_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_bar_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_bar_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bar::MySmallMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bar::MySmallMessage, val_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StringMapEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StringMapEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StringMapEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StringMapEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_EnumMapEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_EnumMapEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_EnumMapEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_EnumMapEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StructMapEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StructMapEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StructMapEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage_StructMapEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, val_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, str_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, enm_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, mysmallmessage_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, enumvec_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, structvec_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, stringmap_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, enummap_),
  PROTOBUF_FIELD_OFFSET(::bar::MyMessage, structmap_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bar::MySmallMessage)},
  { 6, 13, sizeof(::bar::MyMessage_StringMapEntry_DoNotUse)},
  { 15, 22, sizeof(::bar::MyMessage_EnumMapEntry_DoNotUse)},
  { 24, 31, sizeof(::bar::MyMessage_StructMapEntry_DoNotUse)},
  { 33, -1, sizeof(::bar::MyMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bar::_MySmallMessage_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bar::_MyMessage_StringMapEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bar::_MyMessage_EnumMapEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bar::_MyMessage_StructMapEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bar::_MyMessage_default_instance_),
};

const char descriptor_table_protodef_bar_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tbar.proto\022\003bar\"\035\n\016MySmallMessage\022\013\n\003va"
  "l\030\001 \001(\003\"\372\003\n\tMyMessage\022\013\n\003val\030\001 \001(\001\022\013\n\003st"
  "r\030\002 \001(\t\022\030\n\003enm\030\003 \001(\0162\013.bar.MyEnum\022+\n\016myS"
  "mallMessage\030\004 \001(\0132\023.bar.MySmallMessage\022\034"
  "\n\007enumVec\030\005 \003(\0162\013.bar.MyEnum\022&\n\tstructVe"
  "c\030\006 \003(\0132\023.bar.MySmallMessage\0220\n\tstringMa"
  "p\030\007 \003(\0132\035.bar.MyMessage.StringMapEntry\022,"
  "\n\007enumMap\030\010 \003(\0132\033.bar.MyMessage.EnumMapE"
  "ntry\0220\n\tstructMap\030\t \003(\0132\035.bar.MyMessage."
  "StructMapEntry\0320\n\016StringMapEntry\022\013\n\003key\030"
  "\001 \001(\r\022\r\n\005value\030\002 \001(\t:\0028\001\032;\n\014EnumMapEntry"
  "\022\013\n\003key\030\001 \001(\r\022\032\n\005value\030\002 \001(\0162\013.bar.MyEnu"
  "m:\0028\001\032E\n\016StructMapEntry\022\013\n\003key\030\001 \001(\r\022\"\n\005"
  "value\030\002 \001(\0132\023.bar.MySmallMessage:\0028\001*&\n\006"
  "MyEnum\022\r\n\tMY_ENUM_0\020\000\022\r\n\tMy_ENUM_1\020\001b\006pr"
  "oto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_bar_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_bar_2eproto_sccs[5] = {
  &scc_info_MyMessage_bar_2eproto.base,
  &scc_info_MyMessage_EnumMapEntry_DoNotUse_bar_2eproto.base,
  &scc_info_MyMessage_StringMapEntry_DoNotUse_bar_2eproto.base,
  &scc_info_MyMessage_StructMapEntry_DoNotUse_bar_2eproto.base,
  &scc_info_MySmallMessage_bar_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_bar_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_bar_2eproto = {
  false, false, descriptor_table_protodef_bar_2eproto, "bar.proto", 604,
  &descriptor_table_bar_2eproto_once, descriptor_table_bar_2eproto_sccs, descriptor_table_bar_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_bar_2eproto::offsets,
  file_level_metadata_bar_2eproto, 5, file_level_enum_descriptors_bar_2eproto, file_level_service_descriptors_bar_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_bar_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_bar_2eproto)), true);
namespace bar {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MyEnum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_bar_2eproto);
  return file_level_enum_descriptors_bar_2eproto[0];
}
bool MyEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void MySmallMessage::InitAsDefaultInstance() {
}
class MySmallMessage::_Internal {
 public:
};

MySmallMessage::MySmallMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bar.MySmallMessage)
}
MySmallMessage::MySmallMessage(const MySmallMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  val_ = from.val_;
  // @@protoc_insertion_point(copy_constructor:bar.MySmallMessage)
}

void MySmallMessage::SharedCtor() {
  val_ = PROTOBUF_LONGLONG(0);
}

MySmallMessage::~MySmallMessage() {
  // @@protoc_insertion_point(destructor:bar.MySmallMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MySmallMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void MySmallMessage::ArenaDtor(void* object) {
  MySmallMessage* _this = reinterpret_cast< MySmallMessage* >(object);
  (void)_this;
}
void MySmallMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MySmallMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MySmallMessage& MySmallMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MySmallMessage_bar_2eproto.base);
  return *internal_default_instance();
}


void MySmallMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:bar.MySmallMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  val_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MySmallMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int64 val = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          val_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MySmallMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bar.MySmallMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 val = 1;
  if (this->val() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_val(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bar.MySmallMessage)
  return target;
}

size_t MySmallMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bar.MySmallMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 val = 1;
  if (this->val() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_val());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MySmallMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bar.MySmallMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const MySmallMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MySmallMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bar.MySmallMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bar.MySmallMessage)
    MergeFrom(*source);
  }
}

void MySmallMessage::MergeFrom(const MySmallMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bar.MySmallMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.val() != 0) {
    _internal_set_val(from._internal_val());
  }
}

void MySmallMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bar.MySmallMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MySmallMessage::CopyFrom(const MySmallMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bar.MySmallMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MySmallMessage::IsInitialized() const {
  return true;
}

void MySmallMessage::InternalSwap(MySmallMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(val_, other->val_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MySmallMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

MyMessage_StringMapEntry_DoNotUse::MyMessage_StringMapEntry_DoNotUse() {}
MyMessage_StringMapEntry_DoNotUse::MyMessage_StringMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void MyMessage_StringMapEntry_DoNotUse::MergeFrom(const MyMessage_StringMapEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata MyMessage_StringMapEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void MyMessage_StringMapEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

MyMessage_EnumMapEntry_DoNotUse::MyMessage_EnumMapEntry_DoNotUse() {}
MyMessage_EnumMapEntry_DoNotUse::MyMessage_EnumMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void MyMessage_EnumMapEntry_DoNotUse::MergeFrom(const MyMessage_EnumMapEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata MyMessage_EnumMapEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void MyMessage_EnumMapEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

MyMessage_StructMapEntry_DoNotUse::MyMessage_StructMapEntry_DoNotUse() {}
MyMessage_StructMapEntry_DoNotUse::MyMessage_StructMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void MyMessage_StructMapEntry_DoNotUse::MergeFrom(const MyMessage_StructMapEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata MyMessage_StructMapEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void MyMessage_StructMapEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void MyMessage::InitAsDefaultInstance() {
  ::bar::_MyMessage_default_instance_._instance.get_mutable()->mysmallmessage_ = const_cast< ::bar::MySmallMessage*>(
      ::bar::MySmallMessage::internal_default_instance());
}
class MyMessage::_Internal {
 public:
  static const ::bar::MySmallMessage& mysmallmessage(const MyMessage* msg);
};

const ::bar::MySmallMessage&
MyMessage::_Internal::mysmallmessage(const MyMessage* msg) {
  return *msg->mysmallmessage_;
}
MyMessage::MyMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  enumvec_(arena),
  structvec_(arena),
  stringmap_(arena),
  enummap_(arena),
  structmap_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:bar.MyMessage)
}
MyMessage::MyMessage(const MyMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      enumvec_(from.enumvec_),
      structvec_(from.structvec_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  stringmap_.MergeFrom(from.stringmap_);
  enummap_.MergeFrom(from.enummap_);
  structmap_.MergeFrom(from.structmap_);
  str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_str().empty()) {
    str_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_str(),
      GetArena());
  }
  if (from._internal_has_mysmallmessage()) {
    mysmallmessage_ = new ::bar::MySmallMessage(*from.mysmallmessage_);
  } else {
    mysmallmessage_ = nullptr;
  }
  ::memcpy(&val_, &from.val_,
    static_cast<size_t>(reinterpret_cast<char*>(&enm_) -
    reinterpret_cast<char*>(&val_)) + sizeof(enm_));
  // @@protoc_insertion_point(copy_constructor:bar.MyMessage)
}

void MyMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MyMessage_bar_2eproto.base);
  str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&mysmallmessage_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&enm_) -
      reinterpret_cast<char*>(&mysmallmessage_)) + sizeof(enm_));
}

MyMessage::~MyMessage() {
  // @@protoc_insertion_point(destructor:bar.MyMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MyMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  str_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete mysmallmessage_;
}

void MyMessage::ArenaDtor(void* object) {
  MyMessage* _this = reinterpret_cast< MyMessage* >(object);
  (void)_this;
}
void MyMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MyMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MyMessage& MyMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MyMessage_bar_2eproto.base);
  return *internal_default_instance();
}


void MyMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:bar.MyMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  enumvec_.Clear();
  structvec_.Clear();
  stringmap_.Clear();
  enummap_.Clear();
  structmap_.Clear();
  str_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && mysmallmessage_ != nullptr) {
    delete mysmallmessage_;
  }
  mysmallmessage_ = nullptr;
  ::memset(&val_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&enm_) -
      reinterpret_cast<char*>(&val_)) + sizeof(enm_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MyMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double val = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          val_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string str = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_str();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bar.MyMessage.str"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .bar.MyEnum enm = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_enm(static_cast<::bar::MyEnum>(val));
        } else goto handle_unusual;
        continue;
      // .bar.MySmallMessage mySmallMessage = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_mysmallmessage(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .bar.MyEnum enumVec = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_enumvec(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_enumvec(static_cast<::bar::MyEnum>(val));
        } else goto handle_unusual;
        continue;
      // repeated .bar.MySmallMessage structVec = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_structvec(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // map<uint32, string> stringMap = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&stringmap_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      // map<uint32, .bar.MyEnum> enumMap = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&enummap_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else goto handle_unusual;
        continue;
      // map<uint32, .bar.MySmallMessage> structMap = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&structmap_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MyMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bar.MyMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double val = 1;
  if (!(this->val() <= 0 && this->val() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_val(), target);
  }

  // string str = 2;
  if (this->str().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_str().data(), static_cast<int>(this->_internal_str().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bar.MyMessage.str");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_str(), target);
  }

  // .bar.MyEnum enm = 3;
  if (this->enm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_enm(), target);
  }

  // .bar.MySmallMessage mySmallMessage = 4;
  if (this->has_mysmallmessage()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::mysmallmessage(this), target, stream);
  }

  // repeated .bar.MyEnum enumVec = 5;
  {
    int byte_size = _enumvec_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          5, enumvec_, byte_size, target);
    }
  }

  // repeated .bar.MySmallMessage structVec = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_structvec_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_structvec(i), target, stream);
  }

  // map<uint32, string> stringMap = 7;
  if (!this->_internal_stringmap().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, std::string >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< ::PROTOBUF_NAMESPACE_ID::uint32, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "bar.MyMessage.StringMapEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_stringmap().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_stringmap().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, std::string >::const_iterator
          it = this->_internal_stringmap().begin();
          it != this->_internal_stringmap().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = MyMessage_StringMapEntry_DoNotUse::Funcs::InternalSerialize(7, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)].second));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, std::string >::const_iterator
          it = this->_internal_stringmap().begin();
          it != this->_internal_stringmap().end(); ++it) {
        target = MyMessage_StringMapEntry_DoNotUse::Funcs::InternalSerialize(7, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // map<uint32, .bar.MyEnum> enumMap = 8;
  if (!this->_internal_enummap().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MyEnum >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< ::PROTOBUF_NAMESPACE_ID::uint32, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;

    if (stream->IsSerializationDeterministic() &&
        this->_internal_enummap().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_enummap().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MyEnum >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MyEnum >::const_iterator
          it = this->_internal_enummap().begin();
          it != this->_internal_enummap().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = MyMessage_EnumMapEntry_DoNotUse::Funcs::InternalSerialize(8, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MyEnum >::const_iterator
          it = this->_internal_enummap().begin();
          it != this->_internal_enummap().end(); ++it) {
        target = MyMessage_EnumMapEntry_DoNotUse::Funcs::InternalSerialize(8, it->first, it->second, target, stream);
      }
    }
  }

  // map<uint32, .bar.MySmallMessage> structMap = 9;
  if (!this->_internal_structmap().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MySmallMessage >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< ::PROTOBUF_NAMESPACE_ID::uint32, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;

    if (stream->IsSerializationDeterministic() &&
        this->_internal_structmap().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_structmap().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MySmallMessage >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MySmallMessage >::const_iterator
          it = this->_internal_structmap().begin();
          it != this->_internal_structmap().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = MyMessage_StructMapEntry_DoNotUse::Funcs::InternalSerialize(9, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MySmallMessage >::const_iterator
          it = this->_internal_structmap().begin();
          it != this->_internal_structmap().end(); ++it) {
        target = MyMessage_StructMapEntry_DoNotUse::Funcs::InternalSerialize(9, it->first, it->second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bar.MyMessage)
  return target;
}

size_t MyMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bar.MyMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .bar.MyEnum enumVec = 5;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_enumvec_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_enumvec(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _enumvec_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .bar.MySmallMessage structVec = 6;
  total_size += 1UL * this->_internal_structvec_size();
  for (const auto& msg : this->structvec_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // map<uint32, string> stringMap = 7;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_stringmap_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, std::string >::const_iterator
      it = this->_internal_stringmap().begin();
      it != this->_internal_stringmap().end(); ++it) {
    total_size += MyMessage_StringMapEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<uint32, .bar.MyEnum> enumMap = 8;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_enummap_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MyEnum >::const_iterator
      it = this->_internal_enummap().begin();
      it != this->_internal_enummap().end(); ++it) {
    total_size += MyMessage_EnumMapEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<uint32, .bar.MySmallMessage> structMap = 9;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_structmap_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, ::bar::MySmallMessage >::const_iterator
      it = this->_internal_structmap().begin();
      it != this->_internal_structmap().end(); ++it) {
    total_size += MyMessage_StructMapEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string str = 2;
  if (this->str().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_str());
  }

  // .bar.MySmallMessage mySmallMessage = 4;
  if (this->has_mysmallmessage()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *mysmallmessage_);
  }

  // double val = 1;
  if (!(this->val() <= 0 && this->val() >= 0)) {
    total_size += 1 + 8;
  }

  // .bar.MyEnum enm = 3;
  if (this->enm() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_enm());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MyMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bar.MyMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const MyMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MyMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bar.MyMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bar.MyMessage)
    MergeFrom(*source);
  }
}

void MyMessage::MergeFrom(const MyMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bar.MyMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  enumvec_.MergeFrom(from.enumvec_);
  structvec_.MergeFrom(from.structvec_);
  stringmap_.MergeFrom(from.stringmap_);
  enummap_.MergeFrom(from.enummap_);
  structmap_.MergeFrom(from.structmap_);
  if (from.str().size() > 0) {
    _internal_set_str(from._internal_str());
  }
  if (from.has_mysmallmessage()) {
    _internal_mutable_mysmallmessage()->::bar::MySmallMessage::MergeFrom(from._internal_mysmallmessage());
  }
  if (!(from.val() <= 0 && from.val() >= 0)) {
    _internal_set_val(from._internal_val());
  }
  if (from.enm() != 0) {
    _internal_set_enm(from._internal_enm());
  }
}

void MyMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bar.MyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessage::CopyFrom(const MyMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bar.MyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessage::IsInitialized() const {
  return true;
}

void MyMessage::InternalSwap(MyMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  enumvec_.InternalSwap(&other->enumvec_);
  structvec_.InternalSwap(&other->structvec_);
  stringmap_.Swap(&other->stringmap_);
  enummap_.Swap(&other->enummap_);
  structmap_.Swap(&other->structmap_);
  str_.Swap(&other->str_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MyMessage, enm_)
      + sizeof(MyMessage::enm_)
      - PROTOBUF_FIELD_OFFSET(MyMessage, mysmallmessage_)>(
          reinterpret_cast<char*>(&mysmallmessage_),
          reinterpret_cast<char*>(&other->mysmallmessage_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MyMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace bar
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bar::MySmallMessage* Arena::CreateMaybeMessage< ::bar::MySmallMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bar::MySmallMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::bar::MyMessage_StringMapEntry_DoNotUse* Arena::CreateMaybeMessage< ::bar::MyMessage_StringMapEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bar::MyMessage_StringMapEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::bar::MyMessage_EnumMapEntry_DoNotUse* Arena::CreateMaybeMessage< ::bar::MyMessage_EnumMapEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bar::MyMessage_EnumMapEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::bar::MyMessage_StructMapEntry_DoNotUse* Arena::CreateMaybeMessage< ::bar::MyMessage_StructMapEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bar::MyMessage_StructMapEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::bar::MyMessage* Arena::CreateMaybeMessage< ::bar::MyMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bar::MyMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
